### ISSUE TITLE
image different size

### ISSUE THREAD

**Issue by nawafalatwi** [minhnhatnoe/Mondor-Bypass#3]
Hello , you did greet work 

i have an issues with image  size 250x60px 
you can make it like this 
gen.cs
`
                cac.Width = 250;
                cac.Height = 60;
                cac.TextLength = 6;
                cac.FontColor = Color.FromArgb(84, 156, 0); // (100, 100, 100)
                cac.LineNoise = CaptchaImage.lineNoiseLevel.None;
                cac.BackgroundNoise = CaptchaImage.backgroundNoiseLevel.Low;
`

**Comment by minhnhatnoe** [comment]
Sorry about that. We were just solving Mondor captchas on one particular website only, so those parameters were hardcoded such that it best represents the captchas from that website. Feel free to clone this repository and adjust the parameters to suit your needs.

**Comment by nawafalatwi** [comment]
https://github.com/minhnhatnoe/Mondor-Bypass/issues/3#issuecomment-1853375304

yes i know it is hardcoded , and i don't know what i have to change

how do i contact you ?

**Comment by minhnhatnoe** [comment]
I made everything without the intention of changing it later, so it's probably taking some effort to do so. You probably have three options:

1. Resize your input image to the size of mine. This can be done with OpenCV.
2. Use some other models that are already very fine-tuned for these tasks, I'll recommend https://github.com/tesseract-ocr/tesseract because it's quite easy to work with.
3. Keep on with changing my code. You should probably try starting with https://github.com/minhnhatnoe/Mondor-Bypass/blob/d8505e636e2ad3a5a91c8f8ff25e950f0ef8dc4f/src/build/model/models.py#L36C17-L36C17
